### ISSUE TITLE
LastUpdated date is not showing the values correctly

### ISSUE THREAD

**Issue by yeseniamolinab** [yeseniamolinab/covid19-api#1]
All the dates for the `GetStatus` endpoint (`/covid19/status`) are showing the same default value.

**Current response:**
```
[
  {
    "country": "US",
    "lastUpdated": "0001-01-01T00:00:00",
    "cases": 9323852,
    "deaths": 231968,
    "recovered": 3674981
  },
  {
    "country": "IN",
    "lastUpdated": "0001-01-01T00:00:00",
    "cases": 8267623,
    "deaths": 123097,
    "recovered": 7603121
  },
  {
    "country": "BR",
    "lastUpdated": "0001-01-01T00:00:00",
    "cases": 5554206,
    "deaths": 160253,
    "recovered": 5039438
  },
```

Investigate the issue and make a PR to fix it.

**Comment by ralphmcintyre** [comment]
@yeseniamolinab I can look into this.

**Comment by ralphmcintyre** [comment]
@yeseniamolinab Looks like there is a missing model:

![image](https://user-images.githubusercontent.com/8047934/98172400-547d0b80-1ebf-11eb-80c5-ce7a7d538d47.png)

**Comment by yeseniamolinab** [comment]
> @yeseniamolinab Looks like there is a missing model:
> 
> ![image](https://user-images.githubusercontent.com/8047934/98172400-547d0b80-1ebf-11eb-80c5-ce7a7d538d47.png)

Go ahead and fix it 👍
